name: TokenCommands
main: co.mccn.tokencommands.TokenCommands
version: ${project.version}
depend: [TokenAPI]
commands:
  token:
    description: Access Token Commands
    usage: Syntax error! Command is /token [player] [add/set] [-][value]